/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSocialRouteImport } from './routes/_app.social'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreativeRouteImport } from './routes/_app.creative'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppWWsIdRouteImport } from './routes/_app.w.$wsId'
import { Route as AppPostsIdRouteImport } from './routes/_app.posts.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppWWsIdIndexRouteImport } from './routes/_app.w.$wsId.index'
import { Route as ApiPublicSchedulerRunRouteImport } from './routes/api.public.scheduler.run'
import { Route as AppWWsIdTasksRouteImport } from './routes/_app.w.$wsId.tasks'
import { Route as AppWWsIdSuggestionsRouteImport } from './routes/_app.w.$wsId.suggestions'
import { Route as AppWWsIdSocialRouteImport } from './routes/_app.w.$wsId.social'
import { Route as AppWWsIdPostsRouteImport } from './routes/_app.w.$wsId.posts'
import { Route as AppWWsIdMembersRouteImport } from './routes/_app.w.$wsId.members'
import { Route as AppWWsIdCalendarRouteImport } from './routes/_app.w.$wsId.calendar'
import { Route as AppWWsIdAnalyticsRouteImport } from './routes/_app.w.$wsId.analytics'
import { Route as AppWWsIdCategoriesIndexRouteImport } from './routes/_app.w.$wsId.categories.index'
import { Route as AppWWsIdCategoriesCatIdRouteImport } from './routes/_app.w.$wsId.categories.$catId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreativeRoute = AppCreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppWWsIdRoute = AppWWsIdRouteImport.update({
  id: '/w/$wsId',
  path: '/w/$wsId',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIdRoute = AppPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppWWsIdIndexRoute = AppWWsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const ApiPublicSchedulerRunRoute = ApiPublicSchedulerRunRouteImport.update({
  id: '/api/public/scheduler/run',
  path: '/api/public/scheduler/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWWsIdTasksRoute = AppWWsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const AppWWsIdSuggestionsRoute = AppWWsIdSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const AppWWsIdSocialRoute = AppWWsIdSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const AppWWsIdPostsRoute = AppWWsIdPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const AppWWsIdMembersRoute = AppWWsIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const AppWWsIdCalendarRoute = AppWWsIdCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const AppWWsIdAnalyticsRoute = AppWWsIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const AppWWsIdCategoriesIndexRoute = AppWWsIdCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppWWsIdRoute,
} as any)
const AppWWsIdCategoriesCatIdRoute = AppWWsIdCategoriesCatIdRouteImport.update({
  id: '/categories/$catId',
  path: '/categories/$catId',
  getParentRoute: () => AppWWsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/creative': typeof AppCreativeRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/social': typeof AppSocialRoute
  '/tasks': typeof AppTasksRoute
  '/templates': typeof AppTemplatesRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/posts/$id': typeof AppPostsIdRoute
  '/w/$wsId': typeof AppWWsIdRouteWithChildren
  '/w/$wsId/analytics': typeof AppWWsIdAnalyticsRoute
  '/w/$wsId/calendar': typeof AppWWsIdCalendarRoute
  '/w/$wsId/members': typeof AppWWsIdMembersRoute
  '/w/$wsId/posts': typeof AppWWsIdPostsRoute
  '/w/$wsId/social': typeof AppWWsIdSocialRoute
  '/w/$wsId/suggestions': typeof AppWWsIdSuggestionsRoute
  '/w/$wsId/tasks': typeof AppWWsIdTasksRoute
  '/api/public/scheduler/run': typeof ApiPublicSchedulerRunRoute
  '/w/$wsId/': typeof AppWWsIdIndexRoute
  '/w/$wsId/categories/$catId': typeof AppWWsIdCategoriesCatIdRoute
  '/w/$wsId/categories/': typeof AppWWsIdCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/calendar': typeof AppCalendarRoute
  '/creative': typeof AppCreativeRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/social': typeof AppSocialRoute
  '/tasks': typeof AppTasksRoute
  '/templates': typeof AppTemplatesRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/posts/$id': typeof AppPostsIdRoute
  '/w/$wsId/analytics': typeof AppWWsIdAnalyticsRoute
  '/w/$wsId/calendar': typeof AppWWsIdCalendarRoute
  '/w/$wsId/members': typeof AppWWsIdMembersRoute
  '/w/$wsId/posts': typeof AppWWsIdPostsRoute
  '/w/$wsId/social': typeof AppWWsIdSocialRoute
  '/w/$wsId/suggestions': typeof AppWWsIdSuggestionsRoute
  '/w/$wsId/tasks': typeof AppWWsIdTasksRoute
  '/api/public/scheduler/run': typeof ApiPublicSchedulerRunRoute
  '/w/$wsId': typeof AppWWsIdIndexRoute
  '/w/$wsId/categories/$catId': typeof AppWWsIdCategoriesCatIdRoute
  '/w/$wsId/categories': typeof AppWWsIdCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/creative': typeof AppCreativeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/posts/$id': typeof AppPostsIdRoute
  '/_app/w/$wsId': typeof AppWWsIdRouteWithChildren
  '/_app/w/$wsId/analytics': typeof AppWWsIdAnalyticsRoute
  '/_app/w/$wsId/calendar': typeof AppWWsIdCalendarRoute
  '/_app/w/$wsId/members': typeof AppWWsIdMembersRoute
  '/_app/w/$wsId/posts': typeof AppWWsIdPostsRoute
  '/_app/w/$wsId/social': typeof AppWWsIdSocialRoute
  '/_app/w/$wsId/suggestions': typeof AppWWsIdSuggestionsRoute
  '/_app/w/$wsId/tasks': typeof AppWWsIdTasksRoute
  '/api/public/scheduler/run': typeof ApiPublicSchedulerRunRoute
  '/_app/w/$wsId/': typeof AppWWsIdIndexRoute
  '/_app/w/$wsId/categories/$catId': typeof AppWWsIdCategoriesCatIdRoute
  '/_app/w/$wsId/categories/': typeof AppWWsIdCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/calendar'
    | '/creative'
    | '/dashboard'
    | '/notifications'
    | '/social'
    | '/tasks'
    | '/templates'
    | '/workspaces'
    | '/invite/$token'
    | '/admin/users'
    | '/posts/$id'
    | '/w/$wsId'
    | '/w/$wsId/analytics'
    | '/w/$wsId/calendar'
    | '/w/$wsId/members'
    | '/w/$wsId/posts'
    | '/w/$wsId/social'
    | '/w/$wsId/suggestions'
    | '/w/$wsId/tasks'
    | '/api/public/scheduler/run'
    | '/w/$wsId/'
    | '/w/$wsId/categories/$catId'
    | '/w/$wsId/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/calendar'
    | '/creative'
    | '/dashboard'
    | '/notifications'
    | '/social'
    | '/tasks'
    | '/templates'
    | '/workspaces'
    | '/invite/$token'
    | '/admin/users'
    | '/posts/$id'
    | '/w/$wsId/analytics'
    | '/w/$wsId/calendar'
    | '/w/$wsId/members'
    | '/w/$wsId/posts'
    | '/w/$wsId/social'
    | '/w/$wsId/suggestions'
    | '/w/$wsId/tasks'
    | '/api/public/scheduler/run'
    | '/w/$wsId'
    | '/w/$wsId/categories/$catId'
    | '/w/$wsId/categories'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/analytics'
    | '/_app/calendar'
    | '/_app/creative'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/social'
    | '/_app/tasks'
    | '/_app/templates'
    | '/_app/workspaces'
    | '/invite/$token'
    | '/_app/admin/users'
    | '/_app/posts/$id'
    | '/_app/w/$wsId'
    | '/_app/w/$wsId/analytics'
    | '/_app/w/$wsId/calendar'
    | '/_app/w/$wsId/members'
    | '/_app/w/$wsId/posts'
    | '/_app/w/$wsId/social'
    | '/_app/w/$wsId/suggestions'
    | '/_app/w/$wsId/tasks'
    | '/api/public/scheduler/run'
    | '/_app/w/$wsId/'
    | '/_app/w/$wsId/categories/$catId'
    | '/_app/w/$wsId/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicSchedulerRunRoute: typeof ApiPublicSchedulerRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creative': {
      id: '/_app/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof AppCreativeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$wsId': {
      id: '/_app/w/$wsId'
      path: '/w/$wsId'
      fullPath: '/w/$wsId'
      preLoaderRoute: typeof AppWWsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/$id': {
      id: '/_app/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof AppPostsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$wsId/': {
      id: '/_app/w/$wsId/'
      path: '/'
      fullPath: '/w/$wsId/'
      preLoaderRoute: typeof AppWWsIdIndexRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/api/public/scheduler/run': {
      id: '/api/public/scheduler/run'
      path: '/api/public/scheduler/run'
      fullPath: '/api/public/scheduler/run'
      preLoaderRoute: typeof ApiPublicSchedulerRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/w/$wsId/tasks': {
      id: '/_app/w/$wsId/tasks'
      path: '/tasks'
      fullPath: '/w/$wsId/tasks'
      preLoaderRoute: typeof AppWWsIdTasksRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/_app/w/$wsId/suggestions': {
      id: '/_app/w/$wsId/suggestions'
      path: '/suggestions'
      fullPath: '/w/$wsId/suggestions'
      preLoaderRoute: typeof AppWWsIdSuggestionsRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/_app/w/$wsId/social': {
      id: '/_app/w/$wsId/social'
      path: '/social'
      fullPath: '/w/$wsId/social'
      preLoaderRoute: typeof AppWWsIdSocialRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/_app/w/$wsId/posts': {
      id: '/_app/w/$wsId/posts'
      path: '/posts'
      fullPath: '/w/$wsId/posts'
      preLoaderRoute: typeof AppWWsIdPostsRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/_app/w/$wsId/members': {
      id: '/_app/w/$wsId/members'
      path: '/members'
      fullPath: '/w/$wsId/members'
      preLoaderRoute: typeof AppWWsIdMembersRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/_app/w/$wsId/calendar': {
      id: '/_app/w/$wsId/calendar'
      path: '/calendar'
      fullPath: '/w/$wsId/calendar'
      preLoaderRoute: typeof AppWWsIdCalendarRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/_app/w/$wsId/analytics': {
      id: '/_app/w/$wsId/analytics'
      path: '/analytics'
      fullPath: '/w/$wsId/analytics'
      preLoaderRoute: typeof AppWWsIdAnalyticsRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/_app/w/$wsId/categories/': {
      id: '/_app/w/$wsId/categories/'
      path: '/categories'
      fullPath: '/w/$wsId/categories/'
      preLoaderRoute: typeof AppWWsIdCategoriesIndexRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
    '/_app/w/$wsId/categories/$catId': {
      id: '/_app/w/$wsId/categories/$catId'
      path: '/categories/$catId'
      fullPath: '/w/$wsId/categories/$catId'
      preLoaderRoute: typeof AppWWsIdCategoriesCatIdRouteImport
      parentRoute: typeof AppWWsIdRoute
    }
  }
}

interface AppWWsIdRouteChildren {
  AppWWsIdAnalyticsRoute: typeof AppWWsIdAnalyticsRoute
  AppWWsIdCalendarRoute: typeof AppWWsIdCalendarRoute
  AppWWsIdMembersRoute: typeof AppWWsIdMembersRoute
  AppWWsIdPostsRoute: typeof AppWWsIdPostsRoute
  AppWWsIdSocialRoute: typeof AppWWsIdSocialRoute
  AppWWsIdSuggestionsRoute: typeof AppWWsIdSuggestionsRoute
  AppWWsIdTasksRoute: typeof AppWWsIdTasksRoute
  AppWWsIdIndexRoute: typeof AppWWsIdIndexRoute
  AppWWsIdCategoriesCatIdRoute: typeof AppWWsIdCategoriesCatIdRoute
  AppWWsIdCategoriesIndexRoute: typeof AppWWsIdCategoriesIndexRoute
}

const AppWWsIdRouteChildren: AppWWsIdRouteChildren = {
  AppWWsIdAnalyticsRoute: AppWWsIdAnalyticsRoute,
  AppWWsIdCalendarRoute: AppWWsIdCalendarRoute,
  AppWWsIdMembersRoute: AppWWsIdMembersRoute,
  AppWWsIdPostsRoute: AppWWsIdPostsRoute,
  AppWWsIdSocialRoute: AppWWsIdSocialRoute,
  AppWWsIdSuggestionsRoute: AppWWsIdSuggestionsRoute,
  AppWWsIdTasksRoute: AppWWsIdTasksRoute,
  AppWWsIdIndexRoute: AppWWsIdIndexRoute,
  AppWWsIdCategoriesCatIdRoute: AppWWsIdCategoriesCatIdRoute,
  AppWWsIdCategoriesIndexRoute: AppWWsIdCategoriesIndexRoute,
}

const AppWWsIdRouteWithChildren = AppWWsIdRoute._addFileChildren(
  AppWWsIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCreativeRoute: typeof AppCreativeRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppPostsIdRoute: typeof AppPostsIdRoute
  AppWWsIdRoute: typeof AppWWsIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCreativeRoute: AppCreativeRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSocialRoute: AppSocialRoute,
  AppTasksRoute: AppTasksRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppPostsIdRoute: AppPostsIdRoute,
  AppWWsIdRoute: AppWWsIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicSchedulerRunRoute: ApiPublicSchedulerRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
